name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15-intel
          - macos-15

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4

    - name: Test premake5-dev-macos-x86_64
      continue-on-error: true
      run: |
        chmod +x ./premake5-dev-macos-x86_64
        lipo -archs ./premake5-dev-macos-x86_64
        ./premake5-dev-macos-x86_64

    - name: Test premake5-dev-macos-arm64
      continue-on-error: true
      run: |
        chmod +x ./premake5-dev-macos-arm64
        lipo -archs ./premake5-dev-macos-arm64
        ./premake5-dev-macos-arm64

  test-linux:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    - name: Test premake5-dev-linux-x86_64
      continue-on-error: true
      run: |
        file ./premake5-dev-linux-x86_64
        chmod +x ./premake5-dev-linux-x86_64
        ./premake5-dev-linux-x86_64

    - name: Test premake5-dev-linux-arm64
      continue-on-error: true
      run: |
        file ./premake5-dev-linux-arm64
        chmod +x ./premake5-dev-linux-arm64
        ./premake5-dev-linux-arm64

  test-windows:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2025
          - windows-11-arm

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    - name: Test premake5-dev-windows-win32
      continue-on-error: true
      shell: bash
      run: |
        file ./premake5-dev-windows-win32.exe
        ./premake5-dev-windows-win32.exe

    - name: Test premake5-dev-windows-x86_64
      continue-on-error: true
      shell: bash
      run: |
        file ./premake5-dev-windows-x86_64.exe
        ./premake5-dev-windows-x86_64.exe

    - name: Test premake5-dev-windows-arm64
      continue-on-error: true
      shell: bash
      run: |
        file ./premake5-dev-windows-arm64.exe
        ./premake5-dev-windows-arm64.exe
